// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package io.protobj.microserver.net;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Protobuf type {@code com.guangyu.cd003.projects.message.core.net.MQProtocol}
 */
public final class MQProtocol extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.guangyu.cd003.projects.message.core.net.MQProtocol)
        MQProtocolOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use MQProtocol.newBuilder() to construct.
    private MQProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private MQProtocol() {
        msgId_ = "";
        msgData_ = com.google.protobuf.ByteString.EMPTY;
    }

    private transient Object ask;

    @JSONField(deserialize = false)
    public Object getAsk() {
        return ask;
    }

    @JSONField(deserialize = false)
    public void setAsk(Object ask) {
        this.ask = ask;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new MQProtocol();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private MQProtocol(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        msgId_ = s;
                        break;
                    }
                    case 18: {

                        msgData_ = input.readBytes();
                        break;
                    }
                    case 24: {

                        msgix_ = input.readInt32();
                        break;
                    }
                    case 32: {

                        msgKey_ = input.readInt64();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Protocol.internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Protocol.internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        MQProtocol.class, Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile Object msgId_;

    /**
     * <pre>
     * 消息id，图省事直接用消息的简单类名
     * </pre>
     *
     * <code>string msgId = 1;</code>
     *
     * @return The msgId.
     */
    @Override
    public String getMsgId() {
        Object ref = msgId_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            msgId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 消息id，图省事直接用消息的简单类名
     * </pre>
     *
     * <code>string msgId = 1;</code>
     *
     * @return The bytes for msgId.
     */
    @Override
    public com.google.protobuf.ByteString
    getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            msgId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MSGDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msgData_;

    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>bytes msgData = 2;</code>
     *
     * @return The msgData.
     */
    @Override
    public com.google.protobuf.ByteString getMsgData() {
        return msgData_;
    }

    public static final int MSGIX_FIELD_NUMBER = 3;
    private int msgix_;

    /**
     * <pre>
     * 消息序列号
     * </pre>
     *
     * <code>int32 msgix = 3;</code>
     *
     * @return The msgix.
     */
    @Override
    public int getMsgix() {
        return msgix_;
    }

    public static final int MSGKEY_FIELD_NUMBER = 4;
    private long msgKey_;

    /**
     * <pre>
     * 一致性hash时用的key,行会消息就设置为行会id
     * </pre>
     *
     * <code>int64 msgKey = 4;</code>
     *
     * @return The msgKey.
     */
    @Override
    public long getMsgKey() {
        return msgKey_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMsgIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
        }
        if (!msgData_.isEmpty()) {
            output.writeBytes(2, msgData_);
        }
        if (msgix_ != 0) {
            output.writeInt32(3, msgix_);
        }
        if (msgKey_ != 0L) {
            output.writeInt64(4, msgKey_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMsgIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
        }
        if (!msgData_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(2, msgData_);
        }
        if (msgix_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, msgix_);
        }
        if (msgKey_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(4, msgKey_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof MQProtocol)) {
            return super.equals(obj);
        }
        MQProtocol other = (MQProtocol) obj;

        if (!getMsgId()
                .equals(other.getMsgId())) return false;
        if (!getMsgData()
                .equals(other.getMsgData())) return false;
        if (getMsgix()
                != other.getMsgix()) return false;
        if (getMsgKey()
                != other.getMsgKey()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
        hash = (37 * hash) + MSGDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMsgData().hashCode();
        hash = (37 * hash) + MSGIX_FIELD_NUMBER;
        hash = (53 * hash) + getMsgix();
        hash = (37 * hash) + MSGKEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getMsgKey());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static MQProtocol parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static MQProtocol parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MQProtocol parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static MQProtocol parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MQProtocol parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static MQProtocol parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static MQProtocol parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static MQProtocol parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MQProtocol parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static MQProtocol parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static MQProtocol parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static MQProtocol parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(MQProtocol prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code com.guangyu.cd003.projects.message.core.net.MQProtocol}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.guangyu.cd003.projects.message.core.net.MQProtocol)
            MQProtocolOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protocol.internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protocol.internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MQProtocol.class, Builder.class);
        }

        // Construct using com.guangyu.cd003.projects.message.core.net.MQProtocol.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            msgId_ = "";

            msgData_ = com.google.protobuf.ByteString.EMPTY;

            msgix_ = 0;

            msgKey_ = 0L;

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Protocol.internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_descriptor;
        }

        @Override
        public MQProtocol getDefaultInstanceForType() {
            return MQProtocol.getDefaultInstance();
        }

        @Override
        public MQProtocol build() {
            MQProtocol result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public MQProtocol buildPartial() {
            MQProtocol result = new MQProtocol(this);
            result.msgId_ = msgId_;
            result.msgData_ = msgData_;
            result.msgix_ = msgix_;
            result.msgKey_ = msgKey_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof MQProtocol) {
                return mergeFrom((MQProtocol) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(MQProtocol other) {
            if (other == MQProtocol.getDefaultInstance()) return this;
            if (!other.getMsgId().isEmpty()) {
                msgId_ = other.msgId_;
                onChanged();
            }
            if (other.getMsgData() != com.google.protobuf.ByteString.EMPTY) {
                setMsgData(other.getMsgData());
            }
            if (other.getMsgix() != 0) {
                setMsgix(other.getMsgix());
            }
            if (other.getMsgKey() != 0L) {
                setMsgKey(other.getMsgKey());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            MQProtocol parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (MQProtocol) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object msgId_ = "";

        /**
         * <pre>
         * 消息id，图省事直接用消息的简单类名
         * </pre>
         *
         * <code>string msgId = 1;</code>
         *
         * @return The msgId.
         */
        public String getMsgId() {
            Object ref = msgId_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msgId_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 消息id，图省事直接用消息的简单类名
         * </pre>
         *
         * <code>string msgId = 1;</code>
         *
         * @return The bytes for msgId.
         */
        public com.google.protobuf.ByteString
        getMsgIdBytes() {
            Object ref = msgId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msgId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 消息id，图省事直接用消息的简单类名
         * </pre>
         *
         * <code>string msgId = 1;</code>
         *
         * @param value The msgId to set.
         * @return This builder for chaining.
         */
        public Builder setMsgId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msgId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 消息id，图省事直接用消息的简单类名
         * </pre>
         *
         * <code>string msgId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgId() {

            msgId_ = getDefaultInstance().getMsgId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 消息id，图省事直接用消息的简单类名
         * </pre>
         *
         * <code>string msgId = 1;</code>
         *
         * @param value The bytes for msgId to set.
         * @return This builder for chaining.
         */
        public Builder setMsgIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msgId_ = value;
            onChanged();
            return this;
        }

        private com.google.protobuf.ByteString msgData_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * 消息数据
         * </pre>
         *
         * <code>bytes msgData = 2;</code>
         *
         * @return The msgData.
         */
        @Override
        public com.google.protobuf.ByteString getMsgData() {
            return msgData_;
        }

        /**
         * <pre>
         * 消息数据
         * </pre>
         *
         * <code>bytes msgData = 2;</code>
         *
         * @param value The msgData to set.
         * @return This builder for chaining.
         */
        public Builder setMsgData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msgData_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 消息数据
         * </pre>
         *
         * <code>bytes msgData = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgData() {

            msgData_ = getDefaultInstance().getMsgData();
            onChanged();
            return this;
        }

        private int msgix_;

        /**
         * <pre>
         * 消息序列号
         * </pre>
         *
         * <code>int32 msgix = 3;</code>
         *
         * @return The msgix.
         */
        @Override
        public int getMsgix() {
            return msgix_;
        }

        /**
         * <pre>
         * 消息序列号
         * </pre>
         *
         * <code>int32 msgix = 3;</code>
         *
         * @param value The msgix to set.
         * @return This builder for chaining.
         */
        public Builder setMsgix(int value) {

            msgix_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 消息序列号
         * </pre>
         *
         * <code>int32 msgix = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgix() {

            msgix_ = 0;
            onChanged();
            return this;
        }

        private long msgKey_;

        /**
         * <pre>
         * 一致性hash时用的key,行会消息就设置为行会id
         * </pre>
         *
         * <code>int64 msgKey = 4;</code>
         *
         * @return The msgKey.
         */
        @Override
        public long getMsgKey() {
            return msgKey_;
        }

        /**
         * <pre>
         * 一致性hash时用的key,行会消息就设置为行会id
         * </pre>
         *
         * <code>int64 msgKey = 4;</code>
         *
         * @param value The msgKey to set.
         * @return This builder for chaining.
         */
        public Builder setMsgKey(long value) {

            msgKey_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 一致性hash时用的key,行会消息就设置为行会id
         * </pre>
         *
         * <code>int64 msgKey = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgKey() {

            msgKey_ = 0L;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.guangyu.cd003.projects.message.core.net.MQProtocol)
    }

    // @@protoc_insertion_point(class_scope:com.guangyu.cd003.projects.message.core.net.MQProtocol)
    private static final MQProtocol DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new MQProtocol();
    }

    public static MQProtocol getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MQProtocol>
            PARSER = new com.google.protobuf.AbstractParser<MQProtocol>() {
        @Override
        public MQProtocol parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new MQProtocol(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<MQProtocol> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MQProtocol> getParserForType() {
        return PARSER;
    }

    @Override
    public MQProtocol getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

