// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package io.protobj.microserver.net;

public interface MQProtocolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.guangyu.cd003.projects.message.core.net.MQProtocol)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id，图省事直接用消息的简单类名
   * </pre>
   *
   * <code>string msgId = 1;</code>
   * @return The msgId.
   */
  String getMsgId();
  /**
   * <pre>
   *消息id，图省事直接用消息的简单类名
   * </pre>
   *
   * <code>string msgId = 1;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <pre>
   *消息数据
   * </pre>
   *
   * <code>bytes msgData = 2;</code>
   * @return The msgData.
   */
  com.google.protobuf.ByteString getMsgData();

  /**
   * <pre>
   *消息序列号
   * </pre>
   *
   * <code>int32 msgix = 3;</code>
   * @return The msgix.
   */
  int getMsgix();

  /**
   * <pre>
   *一致性hash时用的key,行会消息就设置为行会id
   * </pre>
   *
   * <code>int64 msgKey = 4;</code>
   * @return The msgKey.
   */
  long getMsgKey();
}
