// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package io.protobj.microserver.net;


/**
 * Protobuf type {@code io.protobj.microserver.net.MQProtocol}
 */
public final class MQProtocol {
    private String msgId = "";
    private byte[] msgData;

    private int msgix;

    private long msgKey;

    private MQProtocol() {
    }

    private transient Object ask;

    public Object getAsk() {
        return ask;
    }

    public void setAsk(Object ask) {
        this.ask = ask;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public byte[] getMsgData() {
        return msgData;
    }

    public void setMsgData(byte[] msgData) {
        this.msgData = msgData;
    }

    public int getMsgix() {
        return msgix;
    }

    public void setMsgix(int msgix) {
        this.msgix = msgix;
    }

    public long getMsgKey() {
        return msgKey;
    }

    public void setMsgKey(long msgKey) {
        this.msgKey = msgKey;
    }
}

