// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package io.protobj.microserver.net;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016protocol.proto\022+com.guangyu.cd003.proj" +
      "ects.message.core.net\"K\n\nMQProtocol\022\r\n\005m" +
      "sgId\030\001 \001(\t\022\017\n\007msgData\030\002 \001(\014\022\r\n\005msgix\030\003 \001" +
      "(\005\022\016\n\006msgKey\030\004 \001(\003B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_guangyu_cd003_projects_message_core_net_MQProtocol_descriptor,
        new String[] { "MsgId", "MsgData", "Msgix", "MsgKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
